// <auto-generated />
using CoursesApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Api.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20170831235030_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CoursesApi.Models.EntityModels.CourseNStudent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseName");

                    b.Property<int>("Semester");

                    b.Property<int>("StudentId");

                    b.HasKey("id");

                    b.ToTable("CourseNStudent");
                });

            modelBuilder.Entity("CoursesApi.Models.EntityModels.CourseTemplate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseID");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Semester");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CoursesApi.Models.EntityModels.StudentTemplate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long>("SSN");

                    b.HasKey("id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
